apiVersion: v1
kind: ConfigMap
metadata:
  name: file-service-config
data:
  NODE_ENV: development
  PORT: "3002"
  POSTGRES_DB: files-service
  POSTGRES_USER: admin
  PGDATA: /var/lib/postgresql/data/file
