apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
data:
  POSTGRES_DB: "scheduler-db"
  POSTGRES_HOST: "scheduler-db"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "admin"

  RABBITMQ_DEFAULT_USER: "admin"

  FILE_SERVICE_BASE_URL: "http://file-service:3002"
  RESULT_SERVICE_BASE_URL: "http://result-service:3003"
  SCHEDULER_BASE_URL: "http://scheduler:8001"
  TASK_QUEUE: "default"
  CELERY_CONCURRENCY: "1"
  WORKER_NAME: "celery"
  ZMQ_PORT: "15921"
