apiVersion: v1
kind: ConfigMap
metadata:
  name: results-config
  labels:
    app: results
data:
  NODE_ENV: "development"
  PORT: "3003"

  POSTGRES_DB: "results-service"
  POSTGRES_USER: "admin"
  PGDATA: "/var/lib/postgresql/data/result"
